<?php die(); ?><html>
			<head><title>What to do the day of oral argument - California Appellate Courts</title></head>
				<body class="pdfprnt_print ltr"><div id="content">						<div class="post">
							<div class="entry-header"><h1 class="entry-title">What to do the day of oral argument</h1></div>							<div class="entry-content"><p><div class="flex_column av_one_full  flex_column_div av-zero-column-padding first  " style='border-radius:0px; '><section class="av_textblock_section "  itemscope="itemscope" itemtype="https://schema.org/CreativeWork" ><div class='avia_textblock  '   itemprop="text" ><p><u>What to do the <strong>DAY OF ORAL ARGUMENT</strong></u></p>
<ul>
<li>Arrive at least 30 minutes before your oral argument is scheduled to start. Be sure you go to the location the court sent you for oral argument.</li>
<li>Go through security screening. Before the day of oral argument, check the electronic devices policy on your Court of Appeal’s website to find out if there are any special instructions you need to follow. Some courts send a list of approved electronic devices with notice about the date of oral argument. A party who is presenting oral argument can bring a laptop or tablet into the court. If you have questions about bringing electronic devices into the court, you can contact your Court of Appeal.</li>
<li>Check in with the clerk inside the courtroom. The clerk may ask you to fill out a short form that provides basic information about the case you will be arguing.</li>
<li>The Court of Appeal will probably be hearing another case when you go into the courtroom. Sit quietly and wait.</li>
<li>When your case is called, the appellant and respondent walk to front of the courtroom and sit down at the counsel table facing the justices.</li>
<li>If you’re an appellant, sit on the left.</li>
<li>If you’re a respondent, sit on the right.</li>
<li>If you have a lawyer, the lawyer must sit at the table and present the oral argument. You can go to court for oral argument but you are not required to go if you are represented by a lawyer.</li>
<li>When the presiding justice asks whether your case is ready for argument, announce that you are ready to proceed as the appellant or as the respondent. The appellant will speak first.</li>
<li>When the justices tell you it’s your time to speak, walk to the podium.</li>
<li><em>Do bring</em> your outline of key points to the podium. If your case centers on a statute or contract, also bring a copy of the statute or contract with you to the podium.</li>
<li><em>Do not bring</em> too much paperwork to the podium or to oral argument. In a short amount of time, a lot of papers and transcripts are more likely to get in the way than to help with your argument.</li>
<li>If you would prefer to bring your notes or supporting documents in electronic form, you are permitted to bring a laptop and tablets to the courtroom and to the podium.</li>
<li>Begin talking by saying your name. If you choose, you can start with the customary, “May it please the court, I am . . .” Regardless of how you begin, remember to state your name at the beginning of the argument.</li>
<li>If you do not have a lawyer, you should tell the justices that you are self-represented. The court cannot give you special treatment, but the justices want to know.</li>
<li>You can talk for the exact amount of time given to you by the court. While you talk, the justices may interrupt you and ask questions.</li>
<li>Speak slowly and clearly.</li>
<li>Do not interrupt the justices.</li>
<li>If a justice asks you a question, immediately stop what you were talking about and answer the question as directly as you can. Their questions are likely about the key points in your case, so it’s an opportunity to talk about what will help the justices decide.</li>
<li>If you do not know the answer to a question, tell the truth. Do not misrepresent the facts or law, and do not invent answers.</li>
<li>If you are the appellant, you can divide your time. That means you can spend part of your time talking at the beginning of oral argument and save the other part of your time to talk after the respondent makes their oral argument.</li>
<li>If you are the respondent, you cannot split your time.</li>
<li>At any point you can look back to your outline to make sure you remember all of your important points.</li>
<li>The presiding justice will announce when your time has expired. Immediately stop your argument and go back to your seat at the counsel table.</li>
</ul>
<p><a href="https://selfhelp.appellate.courts.ca.gov//wp-content/uploads/2018/12/what-to-do-the-day-of-oral-argument.pdf" target="_blank" rel="noopener" download="">Get the Step-by-Step Guide on What to Do the Day of Oral Argument (pdf)</a></p>
</div></section></div></p>
</div>
						</div>
					</div></body>
		</html>
<!-- Dynamic page generated in 4.136 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2020-05-11 08:14:57 -->

<!-- Super Cache dynamic page detected but late init not set. See the readme.txt for further details. -->
<!-- Dynamic WPCache Super Cache -->